/** `/tune/ab` — streaming preference collection for the S2 level picker (dev).
 *
 *  v2 flow (Ryan, 2026-08-21): the page generates side-by-side pairs
 *  itself — a sampled view (deck entry + zoom jitter) rendered at the
 *  shipped picker's level vs an adjacent level — and asks which looks
 *  better. No config authoring. Each vote POSTs to the dev middleware
 *  (`/__tune/vote`), appending a JSONL row to git-tracked
 *  the `tune` D1 database; rows carry the features a picker learner
 *  conditions on (viewport dims, zoom, mppx, clip-share-budgeted areaPx,
 *  per-side level/bins/bytes/latency, config snapshot) plus the choice.
 *  Fitting the corpus into picker thresholds happens offline (see
 *  `specs/tune-preference-learning.md`).
 *
 *  v2.1 (same day): informed voting replaces blind — each side shows its
 *  level, px sizes, body/wire bytes, and load time (Ryan: "i'll want to
 *  take those metrics into account"). Richer verdicts for
 *  outside-the-pair sweet spots: 4 = both too coarse (want finer),
 *  5 = both too fine (want coarser), plus an optional free-text note.
 *  The current pair is URL-encoded (`?v=<slug>&z=<zoom>&l=<L>&r=<R>`) so
 *  a case can be revisited/shared, and a history panel lists past votes
 *  with in-place editing (stamping `editedTs`).
 *
 *  v3: votes live in the `tune` D1 database behind the cells-api worker
 *  (`GET/POST /v1/tune/votes`, `PATCH /v1/tune/votes/<id>`), not a
 *  git-tracked JSONL — Ryan: "I definitely don't want a Git-tracked
 *  jsonl pretending to be a DB", and a real DB is what lets others log
 *  in and vote once $oa/auth lands. Writes carry `VITE_TUNE_TOKEN` as a
 *  bearer credential (worker refuses writes when its `TUNE_TOKEN` secret
 *  is unset); reads are public.
 *
 *  v4/v5: views are no longer enumerated. v4 replaced 8 hand-written deck
 *  entries with 42 generated ones; v5 drops the deck entirely and
 *  *samples* — a scope (any of NJ's 586: statewide, 21 counties, 564
 *  munis — `njdot tune scopes`), a viewport, an off-center pan and a zoom,
 *  all continuous. Ryan: "you could just generate views at ~random, not
 *  have to list 42 ahead of time" — and a hand-written list encodes a
 *  guess about which views matter, which is the guess the corpus exists to
 *  test. Sampling is stratified by scope *kind* (per-scope coverage is
 *  unreachable at 586, and the fit conditions on scale regime anyway) and
 *  weighted by √population within a kind (uniform over 564 munis is mostly
 *  empty rural frames; unweighted-by-population is Newark every time).
 *  Votes record the scope slug plus the sampled center/viewport, so any
 *  row reconstructs exactly. History paginates. Fitting is
 *  `njdot tune fit`.
 *
 *  Keys: 1 left · 2 tie · 3 right · 4 finer · 5 coarser · s skip.
 *
 *  Level selection mirrors the prod picker incl. the scoped bins-budget:
 *  `areaPx = min(vpArea, scopeArea/mppx²)` (see `CrashMapSection.
 *  hexPxTarget`) — scoped views use the scope's full admin area rather
 *  than the true `polygon ∩ viewport`; close enough for level choice.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { useUrlStates, defStringParam, floatParam, intParam } from "use-prms"
import { metersPerPixel } from "@/src/map/CrashMap"
import { CELLS_API_BASE } from "@/src/map/config"
import { S2_MAX_LEVEL, S2_MIN_LEVEL, S2_MIN_TARGET_PX, S2_PICK_MULT, S2_TARGET_FACTOR } from "@/src/map/s2"
import { BINS_BUDGET, autoHexPxTarget } from "@/src/map/picker"
import scopesJson from "@/src/map/tune-scopes.json"
import { MiniMap, fmtBytes, pickS2WithOverrides, type MiniMapStats } from "./TunePage"

type ScopeKind = "statewide" | "county" | "muni"

/** One thing the real app can be scoped to: statewide (`/`), a county
 *  (`/c/<county>`), or a muni (`/c/<county>/<muni>`). Generated by
 *  `njdot tune scopes` from the muni boundary file, so centers, areas and
 *  fit-zooms are measured rather than eyeballed. */
type Scope = {
    /** Durable identity, recorded as the vote's `view` and carried by `?v=`. */
    slug: string
    name: string
    kind: ScopeKind
    lat: number
    lon: number
    /** Half-extents of the scope's bbox, so a sampled center offset can stay
     *  inside the thing being scoped to. */
    dlat: number
    dlon: number
    /** Clip-polygon area (km²); null = statewide, i.e. no clip, budget the
     *  whole viewport. */
    km2: number | null
    /** Zoom at which the scope fits `REF_VP`. The sampler refits per viewport
     *  and treats this as the wide end of the range. */
    zoom: number
    pop: number
}

const SCOPES = scopesJson as Scope[]

/** Viewport the stored fit-zooms were computed against (`REF_VP` in
 *  `njdot/cli/tune.py`). */
const REF_VP: [number, number] = [1470, 900]

type VpName = "embed" | "full" | "phone"

const VP_DIMS: Record<VpName, [number, number]> = {
    embed: [1280, 480],
    full: [1470, 900],
    phone: [390, 700],
}
const VP_NAMES = Object.keys(VP_DIMS) as VpName[]
/** URL-param encoding for the viewport (one char). */
const VP_CODES: Record<string, VpName> = { e: "embed", f: "full", p: "phone" }
const vpCode = (vp: VpName) => vp[0]

/** A sampled view: a scope, plus the continuous parameters the picker
 *  actually conditions on. */
type EvalView = {
    scope: Scope
    lat: number
    lon: number
    vp: VpName
}

const SHIPPED = {
    targetFactor: S2_TARGET_FACTOR,
    minTargetPx: S2_MIN_TARGET_PX,
    pickMult: { ...S2_PICK_MULT },
}

/** The prod pick for a view+zoom, plus the intermediate features a
 *  learner would condition on — same math as `CrashMapSection.
 *  hexPxTarget` + `pickS2LevelForPixels`. */
function pickWithFeatures(view: EvalView, zoom: number) {
    const [vpw, vph] = VP_DIMS[view.vp]
    const vpArea = vpw * vph
    const mppx = metersPerPixel(zoom, view.lat)
    let areaPx = vpArea
    if (view.scope.km2 != null) {
        areaPx = Math.min(vpArea, (view.scope.km2 * 1e6) / (mppx * mppx))
    }
    const autoTargetPx = autoHexPxTarget(areaPx, BINS_BUDGET)
    const level = pickS2WithOverrides(autoTargetPx * SHIPPED.targetFactor, zoom, view.lat, SHIPPED.pickMult)
    return { level, mppx, areaPx, autoTargetPx }
}

type Pair = {
    view: EvalView
    zoom: number
    /** Displayed levels; one of them is `prod` (the shipped pick). */
    left: number
    right: number
    prod: number
    feats: { mppx: number; areaPx: number; autoTargetPx: number }
}

function makePair(view: EvalView, zoom: number, left: number, right: number): Pair {
    const { level: prod, ...feats } = pickWithFeatures(view, zoom)
    return { view, zoom, left, right, prod, feats }
}

const SCOPES_BY_KIND: Record<ScopeKind, Scope[]> = {
    statewide: SCOPES.filter(s => s.kind === "statewide"),
    county: SCOPES.filter(s => s.kind === "county"),
    muni: SCOPES.filter(s => s.kind === "muni"),
}
const KINDS = Object.keys(SCOPES_BY_KIND) as ScopeKind[]

/** How far past its fit zoom a scope is sampled. Below the fit zoom the
 *  scope stops filling the frame, so the scoped budget stops describing
 *  what's on screen; above it is just a user zooming in, all the way to
 *  street scale where the `minTargetPx` clamp stops binding. Statewide gets
 *  a symmetric window instead — there's nothing to fit past. */
const ZOOM_WINDOW: Record<ScopeKind, [number, number]> = {
    statewide: [-1.5, 1.5],
    county: [-0.4, 5.0],
    muni: [-0.4, 3.5],
}

const rand = (lo: number, hi: number) => lo + Math.random() * (hi - lo)
const pick = <T,>(xs: T[]): T => xs[Math.floor(Math.random() * xs.length)]

/** Kind with the fewest recorded votes, ties broken at random.
 *
 *  Stratifying by *kind* rather than by individual scope is the point: with
 *  586 scopes, per-scope coverage is unreachable and not what the fit needs
 *  — it conditions on the scale regime (statewide runs above
 *  `autoHexPxTarget`'s clamp, scoped views sit on it), so what has to stay
 *  balanced is the regimes, not the geography. */
function leastVotedKind(counts: Map<string, number>): ScopeKind {
    const votes = (k: ScopeKind) => SCOPES_BY_KIND[k].reduce((n, s) => n + (counts.get(s.slug) ?? 0), 0)
    const min = Math.min(...KINDS.map(votes))
    return pick(KINDS.filter(k => votes(k) === min))
}

/** Population exponent for scope sampling. Uniform over 564 munis draws
 *  mostly rural boroughs with almost no crashes to look at; straight
 *  population would draw Newark every time. Population is a stand-in for
 *  crash count, which is what actually has to be on screen for a
 *  comparison to be judgeable — `MIN_CELLS` catches what slips through. */
const POP_EXP = 0.75

/** Sample a scope within a kind, weighted by `pop ** POP_EXP`. */
function sampleScope(kind: ScopeKind): Scope {
    const pool = SCOPES_BY_KIND[kind]
    const weights = pool.map(s => Math.pow(Math.max(1, s.pop), POP_EXP))
    let r = Math.random() * weights.reduce((a, b) => a + b, 0)
    for (let i = 0; i < pool.length; i++) {
        r -= weights[i]
        if (r <= 0) return pool[i]
    }
    return pool[pool.length - 1]
}

/** Refit a scope's stored zoom (measured against `REF_VP`) to `vp`. */
function fitZoom(scope: Scope, vp: VpName): number {
    const [w, h] = VP_DIMS[vp]
    return scope.zoom + Math.log2(Math.min(w / REF_VP[0], h / REF_VP[1]))
}

/** Sample a view: scope, viewport, off-center pan, and zoom — all
 *  continuous. v4 enumerated 42 views ahead of time; a hand-written list
 *  encodes a guess about which views matter, which is the guess the corpus
 *  exists to test. */
function sampleView(counts: Map<string, number>): { view: EvalView; zoom: number } {
    const kind = leastVotedKind(counts)
    const scope = sampleScope(kind)
    const vp = pick(VP_NAMES)
    const [lo, hi] = ZOOM_WINDOW[kind]
    const zoom = +Math.max(6, Math.min(18, fitZoom(scope, vp) + rand(lo, hi))).toFixed(2)
    // Off-center pan, bounded so the scope still dominates the frame (and,
    // for a scoped view, so the clip polygon still intersects it at all).
    const off = kind === "statewide" ? 0.15 : 0.35
    return {
        view: {
            scope,
            lat: +(scope.lat + rand(-off, off) * scope.dlat).toFixed(4),
            lon: +(scope.lon + rand(-off, off) * scope.dlon).toFixed(4),
            vp,
        },
        zoom,
    }
}

function genPair(counts: Map<string, number> = new Map()): Pair {
    const { view, zoom } = sampleView(counts)
    const { level: prod } = pickWithFeatures(view, zoom)
    // Challenger: an adjacent level, direction random (flipped at the
    // pyramid's edges). Prod-vs-neighbor is exactly the label the
    // learner needs: "was the shipped pick right, or one step off?"
    const dir = Math.random() < 0.5 ? -1 : 1
    const alt = prod + dir >= S2_MIN_LEVEL && prod + dir <= S2_MAX_LEVEL ? prod + dir : prod - dir
    const leftIsProd = Math.random() < 0.5
    return makePair(view, zoom, leftIsProd ? prod : alt, leftIsProd ? alt : prod)
}

/** left/right preference; tie; or "the sweet spot is outside this pair"
 *  directional verdicts (finer = smaller bins than both shown). */
type Choice = "left" | "right" | "tie" | "finer" | "coarser"

const CHOICES: { key: string; choice: Choice | "skip"; label: string }[] = [
    { key: "1", choice: "left", label: "1 ◀ left better" },
    { key: "2", choice: "tie", label: "2 · tie" },
    { key: "3", choice: "right", label: "right better ▶ 3" },
    { key: "4", choice: "finer", label: "4 · neither: want finer" },
    { key: "5", choice: "coarser", label: "5 · neither: want coarser" },
]

type SideRec = { level: number; bins: number | null; bodyBytes: number | null; wireBytes: number | null; ms: number | null }

/** One `picker_votes` row, as the worker's `/v1/tune/votes` returns it
 *  (see `cells-api/src/tune.ts`; SQL columns are flat, the wire shape
 *  nests per-side stats). */
type VoteRow = {
    id: number
    ts: string
    editedTs: string | null
    voter: string | null
    view: string
    lat: number
    lon: number
    zoom: number
    vp: [number, number]
    scopeKm2: number | null
    mppx: number
    areaPx: number
    autoTargetPx: number
    cfg: typeof SHIPPED
    prod: number
    left: SideRec
    right: SideRec
    choice: Choice
    chosen: number | null
    note: string
}

const VOTES_URL = `${CELLS_API_BASE}/v1/tune/votes`

/** Bearer credential for vote writes. Dev-only (`www/.env.local`); the
 *  worker refuses writes when its own `TUNE_TOKEN` secret is unset, so a
 *  build without this just can't vote. */
const TUNE_TOKEN = import.meta.env.VITE_TUNE_TOKEN as string | undefined

async function postJson(url: string, method: "POST" | "PATCH", body: unknown): Promise<void> {
    if (!TUNE_TOKEN) throw new Error("VITE_TUNE_TOKEN unset — see www/.env.local")
    const r = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${TUNE_TOKEN}` },
        body: JSON.stringify(body),
    })
    const json = await r.json().catch(() => ({}))
    if (!r.ok || !json.ok) throw new Error(json.error ?? `HTTP ${r.status}`)
}

type Stats = { left: MiniMapStats | null; right: MiniMapStats | null }

/** History rows per page. The corpus is meant to grow into the hundreds;
 *  rendering all of it under the voting UI buries the pair being judged. */
const PAGE_SIZE = 25

/** Below this many cells on the denser side, there's nothing to have a
 *  preference *about* — a sparse rural draw renders a few sub-pixel dots on
 *  black, and any vote it collects is noise the fit would take seriously.
 *  Auto-resample instead. */
const MIN_CELLS = 400

/** Cap on consecutive auto-resamples, so a bad sampler config or an API
 *  outage surfaces as a visible message rather than an infinite loop. */
const MAX_AUTO_SKIPS = 12

/** URL params, golfed: `v` = scope slug, `z` = zoom, `y`/`x` = sampled
 *  center, `p` = viewport (`e`/`f`/`p`), `l`/`r` = levels. Views are
 *  sampled continuously now, so the center and viewport have to ride along
 *  — the slug alone no longer reconstructs the pair. A missing/unknown `v`
 *  means "no pinned pair"; the page samples one.
 *
 *  Floats use string encoding (`z=11.92`), not the default base64: legible
 *  beats 11 opaque chars in a URL meant to be eyeballed and shared, and 2
 *  decimals of zoom / 4 of lat-lon is all this resolves. */
const URL_PARAMS = {
    v: defStringParam(""),
    z: floatParam({ default: 0, encoding: "string", decimals: 2 }),
    y: floatParam({ default: 0, encoding: "string", decimals: 4 }),
    x: floatParam({ default: 0, encoding: "string", decimals: 4 }),
    p: defStringParam("f"),
    l: intParam(0),
    r: intParam(0),
}

export default function TuneAbPage() {
    const { values: url, setValues: setUrl } = useUrlStates(URL_PARAMS)
    const [pair, setPair] = useState<Pair | null>(() => {
        const scope = SCOPES.find(s => s.slug === url.v)
        if (!scope || !url.z || !url.l || !url.r) return genPair()
        const view: EvalView = {
            scope,
            lat: url.y || scope.lat,
            lon: url.x || scope.lon,
            vp: VP_CODES[url.p] ?? "full",
        }
        return makePair(view, url.z, url.l, url.r)
    })
    const [stats, setStats] = useState<Stats>({ left: null, right: null })
    const [rows, setRows] = useState<VoteRow[]>([])
    const [session, setSession] = useState(0)
    const [note, setNote] = useState("")
    const [saveError, setSaveError] = useState<string | null>(null)
    const [page, setPage] = useState(0)

    /** Votes per deck slug, driving `leastVoted`. Rows from before the
     *  deck regen recorded a display name rather than a slug; they simply
     *  don't match any current entry, which is the right answer — those
     *  views no longer exist at those coordinates. */
    const voteCounts = useMemo(() => {
        const counts = new Map<string, number>()
        for (const row of rows) counts.set(row.view, (counts.get(row.view) ?? 0) + 1)
        return counts
    }, [rows])
    const countsRef = useRef(voteCounts)
    countsRef.current = voteCounts

    /** Votes per scope kind — the balance the sampler is actually steering,
     *  since the fit conditions on scale regime rather than geography. */
    const kindVotes = useMemo(() => {
        const byKind = new Map<ScopeKind, number>()
        for (const [slug, n] of voteCounts) {
            const kind = SCOPES.find(s => s.slug === slug)?.kind
            if (kind) byKind.set(kind, (byKind.get(kind) ?? 0) + n)
        }
        return byKind
    }, [voteCounts])

    useEffect(() => {
        if (!pair) return
        setUrl({
            v: pair.view.scope.slug, z: pair.zoom, y: pair.view.lat, x: pair.view.lon,
            p: vpCode(pair.view.vp), l: pair.left, r: pair.right,
        })
    }, [pair, setUrl])

    const refreshRows = useCallback(() => {
        fetch(VOTES_URL)
            .then(r => r.json())
            .then(json => setRows(json.votes ?? []))
            .catch(err => setSaveError(`load: ${err}`))
    }, [])
    useEffect(() => { refreshRows() }, [refreshRows])

    const next = useCallback(() => {
        setStats({ left: null, right: null })
        setNote("")
        setPair(genPair(countsRef.current))
    }, [])

    // `openRow` and a pinned `?v=` URL are deliberate, so they're exempt from
    // the auto-resample below — otherwise revisiting a sparse case you *want*
    // to look at would bounce you straight off it.
    const [pinned, setPinned] = useState(() => Boolean(url.v && url.z))
    const [autoSkips, setAutoSkips] = useState(0)

    const openRow = useCallback((row: VoteRow) => {
        const scope = SCOPES.find(s => s.slug === row.view)
        if (!scope) return  // legacy row: `view` held a display name, not a slug
        // The row carries the sampled center and viewport, so a continuously
        // sampled view reconstructs exactly — no deck lookup involved.
        const vp = VP_NAMES.find(n => {
            const [w, h] = VP_DIMS[n]
            return w === row.vp[0] && h === row.vp[1]
        }) ?? "full"
        setStats({ left: null, right: null })
        setNote(row.note ?? "")
        setPair(makePair({ scope, lat: row.lat, lon: row.lon, vp }, row.zoom, row.left.level, row.right.level))
    }, [])

    const onLeftStats = useCallback((s: MiniMapStats) => setStats(prev => ({ ...prev, left: s })), [])
    const onRightStats = useCallback((s: MiniMapStats) => setStats(prev => ({ ...prev, right: s })), [])

    const loaded = stats.left !== null && stats.right !== null
    const maxCells = Math.max(stats.left?.cells ?? 0, stats.right?.cells ?? 0)
    const tooSparse = loaded && !pinned && maxCells < MIN_CELLS

    // Resample sparse draws rather than asking for a preference about an empty
    // frame. Bounded so a broken sampler or a dead API shows up as a message.
    useEffect(() => {
        if (!tooSparse || autoSkips >= MAX_AUTO_SKIPS) return
        setAutoSkips(n => n + 1)
        next()
    }, [tooSparse, autoSkips, next])

    const vote = useCallback(async (choice: Choice) => {
        if (!pair || !loaded) return
        const [vpw, vph] = VP_DIMS[pair.view.vp]
        const side = (level: number, s: MiniMapStats | null): SideRec => ({
            level,
            bins: s?.cells ?? null,
            bodyBytes: s?.bodyBytes ?? null,
            wireBytes: s?.wireBytes ?? null,
            ms: s?.ms ?? null,
        })
        const rec = {
            ts: new Date().toISOString(),
            // Slug, not display name: it's the durable identity, it's what
            // `?v=` carries, and it's what `leastVoted` counts.
            view: pair.view.scope.slug,
            lat: pair.view.lat,
            lon: pair.view.lon,
            zoom: +pair.zoom.toFixed(3),
            vp: [vpw, vph],
            scopeKm2: pair.view.scope.km2,
            mppx: +pair.feats.mppx.toFixed(3),
            areaPx: Math.round(pair.feats.areaPx),
            autoTargetPx: +pair.feats.autoTargetPx.toFixed(3),
            cfg: SHIPPED,
            prod: pair.prod,
            left: side(pair.left, stats.left),
            right: side(pair.right, stats.right),
            choice,
            chosen: choice === "left" ? pair.left : choice === "right" ? pair.right : null,
            note: note.trim(),
        }
        try {
            await postJson(VOTES_URL, "POST", rec)
            setSaveError(null)
            setSession(s => s + 1)
            refreshRows()
            next()
        } catch (err) {
            // Leave the pair up — the vote wasn't recorded, so retrying
            // (or skipping) is the user's call.
            setSaveError(String(err))
        }
    }, [pair, stats, loaded, note, next, refreshRows])

    const updateRow = useCallback(async (row: VoteRow, patch: Partial<VoteRow>) => {
        try {
            await postJson(`${VOTES_URL}/${row.id}`, "PATCH", patch)
            setSaveError(null)
            refreshRows()
        } catch (err) {
            setSaveError(String(err))
        }
    }, [refreshRows])

    useEffect(() => {
        const onKey = (e: KeyboardEvent) => {
            const tag = (e.target as HTMLElement)?.tagName
            if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT") return
            const c = CHOICES.find(c => c.key === e.key)
            if (c && c.choice !== "skip") vote(c.choice)
            else if (e.key === "s") next()
        }
        window.addEventListener("keydown", onKey)
        return () => window.removeEventListener("keydown", onKey)
    }, [vote, next])

    const fmtCount = (n: number | null) =>
        n === null ? "?" : n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n)

    // Rows arrive newest-first from D1, so page 0 is the most recent.
    const lastPage = Math.max(0, Math.ceil(rows.length / PAGE_SIZE) - 1)
    const pageStart = Math.min(page, lastPage) * PAGE_SIZE
    const pageRows = rows.slice(pageStart, pageStart + PAGE_SIZE)

    return (
        <div style={{ padding: 12, fontFamily: "sans-serif", color: "#eee", background: "#111", minHeight: "100vh" }}>
            <h1 style={{ fontSize: 18, marginBottom: 4, fontWeight: 500 }}>
                Picker preference stream
                <a href="/tune" style={{ marginLeft: 12, fontSize: 13, color: "#6db3f2" }}>← /tune</a>
            </h1>
            <p style={{ fontSize: 13, color: "#aaa", marginBottom: 12 }}>
                Which binning looks better? <b>1</b> left · <b>2</b> tie · <b>3</b> right ·{" "}
                <b>4</b> neither (finer) · <b>5</b> neither (coarser) · <b>s</b> skip.
                Votes go to the <code>tune</code> D1
                {" · "}{rows.length} all-time · {session} this session
            </p>
            <p style={{ fontSize: 12, color: "#888", marginBottom: 12, fontFamily: "monospace" }}>
                {KINDS.map(k => `${k} ${kindVotes.get(k) ?? 0}`).join(" · ")}
                {" · "}{voteCounts.size} distinct scopes of {SCOPES.length}
            </p>
            {saveError && (
                <div style={{ color: "#e77", fontSize: 13, marginBottom: 8 }}>
                    not saved: {saveError} — retry or press <b>s</b> to skip
                </div>
            )}
            {pair && (
                <div>
                    <div style={{ marginBottom: 8, fontSize: 13, color: "#aaa" }}>
                        <b style={{ color: "#eee" }}>{pair.view.scope.name}</b> · z={pair.zoom.toFixed(2)}
                        {pair.view.scope.km2 != null && ` · scope ${pair.view.scope.km2} km²`}
                        {" · budgeted "}{Math.round(pair.feats.areaPx / 1000)}k px²
                        {" · target "}{pair.feats.autoTargetPx.toFixed(2)}px
                        {pair.feats.autoTargetPx === SHIPPED.minTargetPx && " (at minTargetPx)"}
                        {" · vp "}{VP_DIMS[pair.view.vp].join("×")}
                        {" · "}{voteCounts.get(pair.view.scope.slug) ?? 0} prior votes here
                    </div>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, maxWidth: 1400 }}>
                        {(["left", "right"] as const).map(sideName => {
                            const level = pair[sideName]
                            return (
                                <MiniMap
                                    key={`${sideName}-${pair.view.scope.slug}-${pair.zoom}-${pair.view.lat}-${level}`}
                                    lat={pair.view.lat} lon={pair.view.lon} zoom={pair.zoom} level={level}
                                    renderMode="curve" range={null} dfStart={1} dfEnd={0.5}
                                    onLatLonChange={() => {}}
                                    onStats={sideName === "left" ? onLeftStats : onRightStats}
                                />
                            )
                        })}
                    </div>
                    <div style={{ display: "flex", gap: 8, marginTop: 10, flexWrap: "wrap", alignItems: "center" }}>
                        {CHOICES.map(c => (
                            <button key={c.key} onClick={() => vote(c.choice as Choice)} disabled={!loaded} style={btn(loaded)}>
                                {c.label}
                            </button>
                        ))}
                        <input
                            type="text"
                            placeholder="optional note (recorded with the vote)"
                            value={note}
                            onChange={e => setNote(e.target.value)}
                            style={{ flex: "1 1 240px", minWidth: 200, padding: "5px 8px", background: "#1a1a1a", color: "#eee", border: "1px solid #444", borderRadius: 3, fontSize: 13 }}
                        />
                        <button onClick={next} style={btn(true)}>s · skip</button>
                    </div>
                </div>
            )}
            {rows.length > 0 && (
                <div style={{ marginTop: 24 }}>
                    <div style={{ fontSize: 14, marginBottom: 6, color: "#ccc", display: "flex", gap: 10, alignItems: "center" }}>
                        <span>Vote history ({rows.length})</span>
                        <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0} style={pageBtn(page > 0)}>‹ newer</button>
                        <span style={{ fontFamily: "monospace", fontSize: 12, color: "#888" }}>
                            {pageStart + 1}–{Math.min(rows.length, pageStart + PAGE_SIZE)} of {rows.length}
                        </span>
                        <button onClick={() => setPage(p => Math.min(lastPage, p + 1))} disabled={page >= lastPage} style={pageBtn(page < lastPage)}>older ›</button>
                    </div>
                    <table style={{ borderCollapse: "collapse", fontFamily: "monospace", fontSize: 12 }}>
                        <thead>
                            <tr style={{ color: "#888", textAlign: "left" }}>
                                {["when", "view", "z", "left", "right", "choice", "note", ""].map(h => (
                                    <th key={h} style={{ padding: "2px 10px 2px 0" }}>{h}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                            {pageRows.map(row => (
                                <tr key={row.id} style={{ borderTop: "1px solid #2a2a2a" }}>
                                    <td style={{ padding: "3px 10px 3px 0", color: "#888" }} title={row.ts + (row.editedTs ? ` (edited ${row.editedTs})` : "")}>
                                        {row.ts.slice(5, 16).replace("T", " ")}{row.editedTs ? "*" : ""}
                                    </td>
                                    <td style={{ padding: "3px 10px 3px 0" }} title={row.view}>
                                        {SCOPES.find(s => s.slug === row.view)?.name ?? row.view}
                                    </td>
                                    <td style={{ padding: "3px 10px 3px 0" }}>{row.zoom.toFixed(2)}</td>
                                    {(["left", "right"] as const).map(s => (
                                        <td key={s} style={{ padding: "3px 10px 3px 0", color: row.chosen === row[s].level ? "#7d7" : undefined }}>
                                            l{row[s].level} · {fmtCount(row[s].bins)}
                                            {row[s].wireBytes != null && row[s].wireBytes !== 0 ? ` · ${fmtBytes(row[s].wireBytes)}` : ""}
                                        </td>
                                    ))}
                                    <td style={{ padding: "3px 10px 3px 0" }}>
                                        <select
                                            value={row.choice}
                                            onChange={e => {
                                                const choice = e.target.value as Choice
                                                updateRow(row, {
                                                    choice,
                                                    chosen: choice === "left" ? row.left.level : choice === "right" ? row.right.level : null,
                                                })
                                            }}
                                            style={{ background: "#1a1a1a", color: "#eee", border: "1px solid #444", borderRadius: 3, fontFamily: "monospace", fontSize: 12 }}
                                        >
                                            {(["left", "right", "tie", "finer", "coarser"] as const).map(c => (
                                                <option key={c} value={c}>{c}</option>
                                            ))}
                                        </select>
                                    </td>
                                    <td style={{ padding: "3px 10px 3px 0", color: "#aaa", maxWidth: 280, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={row.note}>
                                        {row.note}
                                    </td>
                                    <td style={{ padding: "3px 0" }}>
                                        <button onClick={() => openRow(row)} style={{ ...btn(true), padding: "2px 8px", fontSize: 12 }}>open</button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    )
}

function pageBtn(enabled: boolean): React.CSSProperties {
    return { ...btn(enabled), padding: "1px 8px", fontSize: 12 }
}

function btn(enabled: boolean): React.CSSProperties {
    return {
        padding: "6px 14px",
        background: "#222",
        color: enabled ? "#eee" : "#666",
        border: "1px solid #555",
        borderRadius: 3,
        cursor: enabled ? "pointer" : "default",
        fontSize: 13,
    }
}
