encryptionsalt: v1:aX/9nnz6qYw=:v1:ltRo+tSmR/8DBo9R:FWcEB4p5G0THqIQDf7chc1orrlh7iw==
config:
  crashes-infra:cloudflare_account_id: 2363642879f18d37d52dca114059937e
  crashes-infra:hccs_zone_id: 584473ace73a57527f4c093c9e2a49f8
  crashes-infra:manage_worker_domains: "true"
  crashes-infra:deployed_workers: crashes-cells-api
